server:
  port: 8080
spring:
#  main:
#    allow-bean-definition-overriding: true  # 忽略重名的feign
#  application:
#    name: mall-goods
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver             # mysql驱动包
    #    driver-class-name: com.mysql.jdbc.Driver
    #    url: jdbc:mysql://192.168.1.11:3306/mall_goods?useSSL=false&serverTimezone=UTC&characterEncoding=utf8              # 数据库名称
    #    url: jdbc:mysql://192.168.1.16:3306/mall_goods?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai       # 数据库名称
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai       # 数据库名称
    username: root
    password: root

mybatis:
  mapper-locations: classpath:com/mall/store/*Mapper.xml
  type-aliases-package: com.mall.store.item.entity